# ndarry 的索引(index),切割(splice)

In [6]:
import numpy as np
arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [7]:
import random
random.randint(50,100)

71

In [12]:
np.random.randint(50,101,size=5)
scores = np.random.randint(50,101,size=(50,5))
scores.size
scores.shape

(50, 5)

In [16]:
scores[:,0]
scores[:,0:1]

array([[ 95],
       [ 81],
       [ 97],
       [ 62],
       [ 83],
       [ 68],
       [ 89],
       [ 74],
       [ 59],
       [ 56],
       [ 69],
       [ 65],
       [ 66],
       [ 85],
       [ 79],
       [ 85],
       [ 94],
       [ 53],
       [ 99],
       [ 80],
       [ 57],
       [ 64],
       [ 56],
       [ 81],
       [ 86],
       [ 64],
       [ 54],
       [ 86],
       [ 85],
       [ 66],
       [ 58],
       [ 90],
       [ 65],
       [ 99],
       [100],
       [ 76],
       [ 67],
       [ 71],
       [ 73],
       [ 75],
       [ 78],
       [100],
       [ 66],
       [ 89],
       [ 72],
       [ 99],
       [ 91],
       [ 55],
       [ 86],
       [ 90]], dtype=int32)

In [19]:
scores[0,:]
scores[0:1,:]

array([[95, 65, 88, 56, 64]], dtype=int32)

In [27]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([73.6, 67.8, 79.2, 70. , 73.2, 74.8, 68.4, 71.8, 75.4, 74.2, 71.8,
       76.6, 68.2, 79.8, 71.4, 76. , 82.4, 71.8, 87.8, 74.2, 61.8, 64. ,
       74. , 79. , 80.4, 62.4, 79. , 77.8, 70. , 78.2, 73.8, 73.8, 65.4,
       84.6, 68.8, 79.8, 73. , 58. , 62. , 83. , 70. , 78.8, 73.8, 85.8,
       66.8, 76. , 70. , 70. , 70.6, 79.2])

In [ ]:
#使用比較運算子
arr = np.random.randn(5)
arr > 0



array([False, False,  True,  True, False])

In [30]:
np.where(arr > 0,1,0)

array([0, 0, 1, 1, 0])

In [31]:
np.where(arr > 0,arr,arr)

array([-1.27849037, -0.39680721,  0.70725467,  0.54674437, -0.87129802])

In [32]:
np.where(arr > 0,1,arr)

array([-1.27849037, -0.39680721,  1.        ,  1.        , -0.87129802])