https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

numpy的索引和切割

In [2]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 98,  81,  62,  74,  93],
       [ 59,  52,  62,  62, 100],
       [ 61,  84,  67,  99,  66],
       [ 69,  58,  59,  93,  99],
       [100,  50,  80,  65,  67]], dtype=int32)

In [4]:
scores[:3,2:]

array([[ 62,  74,  93],
       [ 62,  62, 100],
       [ 67,  99,  66]], dtype=int32)

In [6]:
scores[4].shape

(5,)

In [7]:
scores[4]

array([100,  50,  80,  65,  67], dtype=int32)

In [8]:
scores[4,:]

array([100,  50,  80,  65,  67], dtype=int32)

In [9]:
scores[4:,:]

array([[100,  50,  80,  65,  67]], dtype=int32)

In [10]:
scores[:,:2]

array([[ 98,  81],
       [ 59,  52],
       [ 61,  84],
       [ 69,  58],
       [100,  50]], dtype=int32)

In [ ]:
### numpy的統計工具

In [11]:
scores = np.random.randint(50,101,size=(5,5))
scores


array([[96, 82, 50, 51, 51],
       [73, 73, 63, 62, 92],
       [78, 57, 57, 84, 63],
       [74, 89, 79, 96, 88],
       [85, 90, 60, 70, 79]], dtype=int32)

In [12]:
scores[:,0]+scores[:,1]+scores[:,2]+scores[:,3]+scores[:,3]

array([330, 333, 360, 434, 375], dtype=int32)

In [ ]:
###加總
np.sum(scores,axis=1)

array([330, 363, 339, 426, 384])

In [14]:
###平均
np.mean(scores,axis=1)

array([66. , 72.6, 67.8, 85.2, 76.8])

In [15]:
###最大
np.max(scores,axis=1)

array([96, 92, 84, 96, 90], dtype=int32)

In [16]:
###最小
np.min(scores,axis=1)

array([50, 62, 57, 74, 60], dtype=int32)

In [17]:
###中間數
np.median(scores,axis=1)

array([51., 73., 63., 88., 79.])

In [18]:
###標準差
np.std(scores,axis=1)

array([19.29766825, 10.78146558, 11.16064514,  7.78203058, 10.72194012])