https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [4]:
import numpy as np
np.array([1,3,5,7,9])




array([1, 3, 5, 7, 9])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
 np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.arange(0,1,0.5)

array([0. , 0.5])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.rand(3,4)

array([[0.29834315, 0.94840854, 0.73995402, 0.68872026],
       [0.29936632, 0.32842477, 0.39759067, 0.1066347 ],
       [0.89213057, 0.68637044, 0.59539935, 0.86210225]])

In [15]:
np.random.randint(50,101,size=(50,5))

array([[ 89,  67,  57,  61,  72],
       [ 77,  55,  76,  77,  79],
       [ 63,  58,  78,  86,  99],
       [ 85,  67,  57,  60,  59],
       [ 59,  98,  82,  53,  57],
       [ 80,  98,  61,  51,  84],
       [ 63,  95,  66,  61,  59],
       [ 97,  76,  56,  61,  72],
       [ 77,  66,  87,  62,  92],
       [ 82,  66,  73,  97,  96],
       [ 52,  71,  82,  79,  50],
       [ 93,  96,  55,  58,  58],
       [ 92,  92,  61,  94,  91],
       [ 56,  79,  78,  94,  90],
       [ 85,  75,  74,  65,  61],
       [ 61,  61,  60,  82,  82],
       [ 78,  62,  73,  86,  73],
       [ 89,  96,  68,  85,  83],
       [ 60,  83,  60,  75,  75],
       [ 59,  82,  62,  52,  73],
       [ 52,  51,  80,  65,  88],
       [ 64,  67,  99,  65,  82],
       [ 71,  66,  68,  98,  92],
       [ 71,  86,  60,  60,  61],
       [ 71,  98,  64,  94,  62],
       [ 83,  69,  98,  79,  76],
       [ 57,  69,  90,  50,  70],
       [ 87,  99,  55,  87,  61],
       [ 79,  57,  97,  91,  78],
       [ 94,  